### ISSUE TITLE
Resource Window: "Apply track template to selected tracks" not working correctly

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1109]
Had to keep the topic short, sorry.

The issue is: when a track already has Kontakt loaded and you click on "apply to selectes tracks", the track template (also consisting of a Kontakt instance) is not loaded, because Kontakt is already in the FX slot. However, the expected behavior would be to load the track template in any case.

**Comment by nofishonfriday** [comment]
Confirmed.
As further info, it's not a Kontakt specific issue, I can also reproduce with e.g. ReaSynth.

**Comment by StephanRoemer** [comment]
Thanks for confirming nofish!

**Comment by nofishonfriday** [comment]
edit:
Wait, rethinking this, I guess _apply_ actually means _replace_ here, so 'replace current track state with track template x', then current behaviour would make sense. On further thought, this seems to make sense indeed as track templates store all kinds of other things in addition to FX (e.g. track volume), so there can't really be a 'merge' (paste) track template functionality (how to resolve conflicting settings?) as there's with FX chains.

Does this seem to mae sense to you?

**Comment by StephanRoemer** [comment]
Hmm, sorry you lost me. To me, apply should behave like replace. If I want to apply a track template on an track, everything else on that track should be discarded. Does this make sense? :D

**Comment by nofishonfriday** [comment]
> apply should behave like replace. If I want to apply a track template on an existing track, everything else on that track should be discarded.

That's what I was trying to say above. :D 
And I think that's actually what's happening (here at least).

To illustrate, example with ReaSynth:
ReaSynth loaded on track, apply track template which has a ReaSynth instance -> existing instance gets replaced with the one in the track template.
To show the instances are really replace I renamed the one in the track template as 'ReaSynth from track template'.

![apply track template](https://user-images.githubusercontent.com/7658194/52915670-34667c80-32d7-11e9-8840-7db562b73424.gif)

Is it different with Kontakt, or is there some miscommunication?

**Comment by StephanRoemer** [comment]
Sorry, haven't slept enough today, maybe that's the reason! 😄 
It's indeed different here, the name of the track is replace, but the instrument remains the same:

https://i.imgur.com/z3yllqM.gif

**Comment by nofishonfriday** [comment]
Ok, got it. Thanks for the screencapture.

**Comment by StephanRoemer** [comment]
Awesome! 👍

**Comment by nofishonfriday** [comment]
Er...not to get hopes too high, I mean I now get what the issue is, not that I've solved / fixed it (currently). :) 

Just to confirm, loading track templates with Kontakt via Reaper's native functionality (Insert track from template) works as it should I guess?

**Comment by StephanRoemer** [comment]
Yes, that works as expected, since it always creates a new track.

**Comment by nofishonfriday** [comment]
@StephanRoemer 
I can reproduce this with Kontakt if 'Avoid loading undo states when possible' is enabled for it.
If I disable this, the track template gets applied correctly (i.e. an existing Kontakt patch gets replaced with the one in the track template).

Can you check if this is the case on your side too?
(If so, not suggesting disabling 'Avoid loading undo states when possible' will be the cure, but we would at least know the culprit for starters.)

**Comment by nofishonfriday** [comment]
I'll copy @cfillion's findings via Slack here so they don't get lost:

>confirmed with just reaeq + "Avoid loading undo states when possible" enabled
>looks like a bug to me, but setting the effect offline first seems to work around it (

```
t = reaper.GetTrack(0, 0)
_, c = reaper.GetTrackStateChunk(t, '')

-- (reset or tweak the effect before the next line)

reaper.SetTrackStateChunk(t, c)

-- result: effect settings are not replaced if "Avoid loading undo states when possible" is enabled
-- unless the effect is set offline first

reaper.TrackFX_SetOffline(t, 0, true)
reaper.SetTrackStateChunk(t, c) -- works now
```

[Bugreport in Reaper forum](https://forum.cockos.com/showthread.php?t=217691)

**Comment by StephanRoemer** [comment]
Sorry nofish, didn't have the time yet to check. Reaper machine was off for some days. Will check today and report back!

**Comment by StephanRoemer** [comment]
Okay, finally got the time to test this and yes, you are right, disabling "avoid loading undo states" fixes it!

**Comment by nofishonfriday** [comment]
Thanks.
Currently waiting for a reaction from Cockos, see link to BR above.
(Feel free to bump if you like :))

**Comment by StephanRoemer** [comment]
Done! :)

**Comment by nofishonfriday** [comment]
@StephanRoemer 
As there's no reaction from Cockos so far, could you test this build and let me know if it works for you?
https://www.dropbox.com/s/pk4uwatr38lqdbh/reaper_sws64.dll?dl=1

Note:
It seems there's a negative side effect in that track template applying takes a (noticeable) bit longer now, as the track FX are set offline now before loading the template (to force updating, see https://github.com/reaper-oss/sws/issues/1109#issuecomment-467054017) which seems especially noticeable with Kontakt.
But I don't know of any other approach currently. (Actually I still think it should rather be fixed in Reaper but alas...).

**Comment by StephanRoemer** [comment]
It works! And funnily, I didn't notice any lag when applying a track template. It even made the impression on me, that it's faster now. Awesome fix nofish 👍

**Comment by nofishonfriday** [comment]
@StephanRoemer 
I noticed that previous version created unwanted additional undo points (when setting the FX offline before applying track template), so I've tweaked it a bit (to not create these undo points).

Link above is updated with new version, if you could d/l and test again if it still works for you, that would be nice.
Thanks.

**Comment by StephanRoemer** [comment]
Awesome, let me check...

Yep, works as expected!

**Comment by StephanRoemer** [comment]
I don't know why, but with the last devs this issue is back. Applying track templates only changes the name of the track.

**Comment by nofishonfriday** [comment]
Are you using seperate installs by chance?
If so, please do the following in the non-working install:
disable 'avoid loading undo states', apply / ok, enable it again, apply / ok

Now try again, working now?

background:
The fix checks in `reaper-fxoptions.ini` if there's an entry for a specific plugin (which gets written with above disabling / enabling) and according to that works around the track template loading bug. That's the 'best' we can do I think from SWS side.
Do you see an entry `Kontakt.dll=256` (or similar) in `reaper-fxoptions.ini `?

**Comment by StephanRoemer** [comment]
It's the same install, just with a newer dev release installed.

I tried the disable/enable of avoid undo states. Didn't work. What worked however, was disabling the undo states. Then everything works as expected.

When enabling "avoid undo states", I get a Kontakt.dll=256 in the reaper-fxoptions.ini in [safemode].
Not sure if that helps.

**Comment by nofishonfriday** [comment]
Hm, on a quick test it still works here with Reaper 5.977+dev0509 also with 'avoid loading undo states' enabled (which is actually the point of this fix.),.
Any chance you changed SWS versions meanwhile?

The one I sent you which contains this fix should say `Version 2.10.0 #1 built on Mar 5 2019` in Extensions -> About SWS extension

**Comment by StephanRoemer** [comment]
I'm using the one from April 1st, which included some changes in the ressources window:
https://github.com/reaper-oss/sws/issues/1119#issuecomment-478396026

Does this version not include the fix?

**Comment by nofishonfriday** [comment]
Ah this explains it. :)
No it doesn't contain this fix, different development branches.

I'll make one which combines them, stay tuned.

**Comment by nofishonfriday** [comment]
https://www.dropbox.com/s/jbih0yu6f6caxay/reaper_sws64.dll?dl=1

This contains the fix for this issue + the [Resources window tweaks ](https://github.com/reaper-oss/sws/issues/1119) (don't block Del key + Enter focuses list).
The AND keyword support for the filter is removed because agreed with your thoughts, we should do a more proper solution (https://github.com/reaper-oss/sws/issues/1119#issuecomment-493083501).

**Comment by StephanRoemer** [comment]
AWESOME! Love the Focus Enter Key! Thanks nofish!
Actually the AND and OR solution wasn't bad, just that OR was the default mode instead of AND :P

**Comment by nofishonfriday** [comment]
closing because [fixed in REAPER](https://forum.cockos.com/showpost.php?p=2169479&postcount=1).
