### ISSUE TITLE
 Send gets deleted when using SWS "Show vol env for last adjusted send"

### ISSUE THREAD

**Issue by ericzang** [reaper-oss/sws#1183]
Concerning the following actions:
SWS/BR: Show/hide volume track envelope for last adjusted send
SWS/BR: Show/hide track envelope for last adjusted send (volume/pan only)

The send of a track gets deleted when the previous track's corresponding send has the above action applied.

Under this condition:
Preferences > Automation > When adding volume/pan envelopes, apply trim to envelope and reset trim: Never or In read/write.

"Always" setting is ok.

Tested with a portable install, default config.

See screen capture.
https://drive.google.com/open?id=1JDLfRfIMCYgmTjkw0EhNBLCC1_zP7-o8

Thanks!

**Comment by ericzang** [comment]
Corrected link:
https://drive.google.com/open?id=1JDLfRfIMCYgmTjkw0EhNBLCC1_zP7-o8

**Comment by cfillion** [comment]
The issue should be fixed in this test build: <https://ci.appveyor.com/api/buildjobs/df51sm40gx51qocl/artifacts/build%2Freaper_sws64.dll>.

**Comment by ericzang** [comment]
excellent thanks!!!

**Comment by wonder6oy** [comment]
Hello SWS team.  I am having a similar problem with the action:

SWS/BR: Toggle show volume send envelopes for selected tracks

When I toggle to show, all works as expected, but when I toggle to hide, all the send levels are reduced to zero.  I tried out the test build above, but the problem remains.

**Comment by cfillion** [comment]
@wonder6oy Could it be the send volume envelope contained only one point at -inf and "When adding volume/pan envelopes, apply trim to envelope and reset trim" is set to either "Always" or "In read/write" in Preferences > Editing Behavior > Automation? If so, this is the expected behavior.
